# Generated by Django 4.2.19 on 2026-03-06 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("project_proposal", "Project Proposal"),
                            ("payment_requisition", "Payment Requisition"),
                            ("caution_refund", "Caution Refund"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_l1", "Pending L1"),
                            ("pending_l2", "Pending L2"),
                            ("approved", "Approved"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("requires_l2", models.BooleanField(default=False)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "l1_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_info", "More Info Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("l1_decided_at", models.DateTimeField(blank=True, null=True)),
                ("l1_notes", models.TextField(blank=True)),
                (
                    "l2_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_info", "More Info Requested"),
                        ],
                        max_length=20,
                    ),
                ),
                ("l2_decided_at", models.DateTimeField(blank=True, null=True)),
                ("l2_notes", models.TextField(blank=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "l1_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l1_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "l2_approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l2_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "approvals_workflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("info_request", "Info Request"),
                            ("info_response", "Info Response"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="approvals.approvalworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "approvals_comment",
                "ordering": ["created_at"],
            },
        ),
    ]
