# Generated by Django 4.2.19 on 2026-03-07 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("shortlets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("electrical", "Electrical"),
                            ("plumbing", "Plumbing"),
                            ("hvac", "HVAC / Air Conditioning"),
                            ("structural", "Structural"),
                            ("appliance", "Appliance"),
                            ("cleaning", "Cleaning"),
                            ("security", "Security"),
                            ("it", "IT / Network"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("property", "Shortlet Property"),
                            ("project_site", "Project Site"),
                            ("office", "Office"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_details", models.CharField(blank=True, max_length=300)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("pending_parts", "Pending Parts"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("assignment_notes", models.TextField(blank=True)),
                ("expected_resolution_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "labor_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "parts_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_assigned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="projects.project",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_requests",
                        to="shortlets.shortletproperty",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_request",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceStatusUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("parts_needed", models.JSONField(default=list)),
                ("parts_vendor", models.CharField(blank=True, max_length=200)),
                (
                    "parts_estimated_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("parts_expected_delivery", models.DateField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="maintenance.maintenancerequest",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_status_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_status_update",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MaintenancePhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.CharField(max_length=500)),
                ("caption", models.CharField(blank=True, max_length=100)),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="maintenance.maintenancerequest",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_photo",
            },
        ),
        migrations.RunSQL(
            sql="CREATE SEQUENCE IF NOT EXISTS maintenance_request_code_seq;",
            reverse_sql="DROP SEQUENCE IF EXISTS maintenance_request_code_seq;",
        ),
    ]
